bootJar {
    mainClass = 'ec.todoecuador.authorizationserver.AuthorizationServerApplication'
}

dependencies {
    implementation "org.springframework.boot:spring-boot-starter-oauth2-authorization-server"
    implementation "org.springframework.boot:spring-boot-starter-jdbc"
    implementation "org.postgresql:postgresql"
    implementation "org.flywaydb:flyway-core"
}