spring.application.name=authorization-server
spring.config.import=configserver:
spring.cloud.config.uri=${CONFIG_SERVER_URL:http://localhost:8888}
spring.cloud.config.username=${CONFIG_SERVER_USERNAME:config_user}
spring.cloud.config.password=${CONFIG_SERVER_PASSWORD}
spring.cloud.config.fail-fast=true
spring.cloud.config.retry.max-attempts=30
spring.cloud.config.retry.initial-interval=2000
